import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import CursorEffects from "./components/CursorEffects";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-900 text-white">
        <CursorEffects />

          <div className="min-h-screen max-w-screen-xl mx-auto px-6 py-12 md:px-12 md:py-16 lg:py-0">
            <div className="flex flex-col  gap-16 lg:flex-row lg:justify-between lg:gap:4">
              <Sidebar />

              <main className="flex-1 pt-24 lg:py-24">{children}</main>
            </div>
          </div>
        
      </body>
    </html>
  );
}
